<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'dashboard',
                'icon' => 'mdi-view-dashboard',
                'url' => '/dashboard',
                'permission' => null,
                'parent_id' => null,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 2,
                'name' => 'Pages',
                'icon' => 'mdi-file-document-edit',
                'url' => '/pages',
                'permission' => 'page.view',
                'parent_id' => 7,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 3,
                'name' => 'Users',
                'icon' => 'mdi-account-multiple',
                'url' => null,
                'permission' => 'user.view',
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 4,
                'name' => 'users',
                'icon' => 'mdi-account',
                'url' => '/users',
                'permission' => 'user.view',
                'parent_id' => 3,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 5,
                'name' => 'Roles',
                'icon' => 'mdi-account-check',
                'url' => '/roles',
                'permission' => 'role.view',
                'parent_id' => 3,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 6,
                'name' => 'Permissions',
                'icon' => 'mdi-account-details',
                'url' => '/permissions',
                'permission' => 'permission.view',
                'parent_id' => 3,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 7,
                'name' => 'system',
                'icon' => 'mdi-cog-box',
                'url' => null,
                'permission' => 'setting.view',
                'parent_id' => null,
                'order' => 3,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 8,
                'name' => 'settings',
                'icon' => 'mdi-cog',
                'url' => '/settings',
                'permission' => 'setting.update',
                'parent_id' => 7,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 9,
                'name' => 'Menu',
                'icon' => 'mdi-format-list-bulleted-square',
                'url' => '/menus',
                'permission' => 'menu.view',
                'parent_id' => 7,
                'order' => 1,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 10,
                'name' => 'log_activity',
                'icon' => 'mdi-database-eye',
                'url' => '/logs',
                'permission' => 'log.view',
                'parent_id' => 7,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 11,
                'name' => 'Backup DB',
                'icon' => 'mdi-database',
                'url' => '/backups',
                'permission' => 'backup.view',
                'parent_id' => 7,
                'order' => 3,
                'is_active' => 1,
                'is_system' => 1,
                'created_at' => null,
                'updated_at' => Carbon::parse('2025-07-29 03:12:57'),
            ],
            [
                'id' => 12,
                'name' => 'Product',
                'icon' => 'mdi-package-variant-closed',
                'url' => '/product',
                'permission' => 'product.view',
                'parent_id' => null,
                'order' => 0,
                'is_active' => 1,
                'is_system' => 0,
                'created_at' => Carbon::parse('2025-12-21 13:25:01'),
                'updated_at' => Carbon::parse('2025-12-21 13:25:01'),
            ],
            [
                'id' => 13,
                'name' => 'Purchase',
                'icon' => 'mdi-cart',
                'url' => '/purchases',
                'permission' => 'purchase.view',
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
                'is_system' => 0,
                'created_at' => Carbon::parse('2025-12-21 13:25:01'),
                'updated_at' => Carbon::parse('2025-12-21 13:25:01'),
            ],
        ]);
    }
}